package const
const val WebClientId = "104401303739-ttunqfkhu61pnpldnq0fdmi644ctn3ng.apps.googleusercontent.com"
const val NEWS_DISPLAYING_ERROR = "Error in news displaying"
const val SOMETHING_WENT_WRONG_ERROR  = "Something went wrong in news displaying"
const val SOMETHING_WENT_WRONG_IN_DATA = "Something went wrong,while displaying data"
const val WAITING_TEXT = "Waiting for your Internet"
const val CORRECTION_ERROR = "Your internet is not working correctly"
const val ALREADY_HAVE_ACCOUNT = "Already have account?"
const val PASSWORD = "Password"
const val ENTER_YOUR_PASSWORD = "Enter your password"
const val NAME = "Name"
const val YOUR_NAME = "Your Name"
const val EMAIL = "Email"
const val ENTER_EMAIL = "Enter Email"
const val SIGN_UP = "SIGN UP"
const val SIGN_IN = "SIGN IN"
const val AUTHENTICATION_ERROR = "Something went wrong while authentication"
